vich_uploader:
    db_driver: orm
    
    metadata:
        type: attribute

    mappings:
        artiste_image:
            uri_prefix: /uploads/artistes
            upload_destination: '%kernel.project_dir%/public/uploads/artistes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
